#!/usr/bin/env bash
set -euo pipefail

# Run this script inside an empty local repository folder.
# Example:
#   mkdir linux-hardening-audit-toolkit
#   cd linux-hardening-audit-toolkit
#   git remote add origin https://github.com/RM7hsh/linux-hardening-audit-toolkit.git
#   bash create_project.sh
#   git push --all origin
#   git push --tags origin

GIT_NAME="Rajabali Rahimov"
GIT_EMAIL="radzabali2007@gmail.com"

if [ ! -d .git ]; then
  git init -b main
else
  git branch -M main || true
fi

git config user.name "$GIT_NAME"
git config user.email "$GIT_EMAIL"

write_file() {
  local path="$1"
  mkdir -p "$(dirname "$path")"
  cat > "$path"
}

commit_all() {
  local message="$1"
  git add .
  if ! git diff --cached --quiet; then
    git commit -m "$message"
  fi
}

# -----------------------------------------------------------------------------
# 1. Initial commit
# -----------------------------------------------------------------------------

write_file .gitignore <<'EOF'
# Local files
.DS_Store
*.log
*.tmp
*.bak
*.swp
*.swo
.env
.env.*
!.env.example

# Python
__pycache__/
*.pyc
.pytest_cache/
.mypy_cache/
.ruff_cache/
.venv/
venv/

# Build artifacts
build/
dist/
*.egg-info/

# Reports generated by the tool
reports/*.json
reports/*.md
reports/*.html
!reports/.gitkeep
EOF

mkdir -p reports
: > reports/.gitkeep

write_file README.md <<'EOF'
# Linux Hardening Audit Toolkit

Linux security baseline audit toolkit for checking SSH, firewall, users, sudo, services, open ports, updates, disk usage, logs and systemd health.

This repository is a portfolio project focused on Linux administration, security auditing and practical infrastructure operations.
EOF

commit_all "Initial commit: Add README, gitignore and reports directory"

git checkout -b develop

# -----------------------------------------------------------------------------
# 2. Feature: initial Python CLI with basic checks
# -----------------------------------------------------------------------------

git checkout -b feature/initial-audit-cli

write_file pyproject.toml <<'EOF'
[project]
name = "linux-hardening-audit-toolkit"
version = "0.1.0"
description = "Linux security baseline audit toolkit"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
lhat = "lhat.cli:main"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]
EOF

mkdir -p lhat/checks tests
write_file lhat/__init__.py <<'EOF'
"""Linux Hardening Audit Toolkit."""
EOF

write_file lhat/models.py <<'EOF'
from dataclasses import dataclass
from enum import Enum


class Status(str, Enum):
    PASS = "PASS"
    WARN = "WARN"
    FAIL = "FAIL"
    INFO = "INFO"


@dataclass(frozen=True)
class CheckResult:
    check_id: str
    title: str
    status: Status
    message: str
    remediation: str = ""
EOF

write_file lhat/runner.py <<'EOF'
import json
from pathlib import Path

from lhat.checks import disk, firewall, ports, services, ssh, sudo, updates, users
from lhat.models import CheckResult


CHECK_MODULES = [
    ssh,
    firewall,
    users,
    sudo,
    services,
    ports,
    updates,
    disk,
]


def run_all_checks(root: Path = Path("/")) -> list[CheckResult]:
    results: list[CheckResult] = []
    for module in CHECK_MODULES:
        results.extend(module.run(root=root))
    return results


def to_json(results: list[CheckResult]) -> str:
    return json.dumps([result.__dict__ for result in results], indent=2, ensure_ascii=False)


def to_markdown(results: list[CheckResult]) -> str:
    lines = ["# Linux Hardening Audit Report", ""]
    lines.append("| Check | Status | Message |")
    lines.append("|---|---|---|")
    for result in results:
        lines.append(f"| {result.check_id} | {result.status} | {result.message} |")
    return "\n".join(lines) + "\n"
EOF

write_file lhat/cli.py <<'EOF'
import argparse
from pathlib import Path

from lhat.runner import run_all_checks, to_json, to_markdown


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Linux hardening audit toolkit")
    parser.add_argument("--root", default="/", help="Root directory to inspect")
    parser.add_argument("--format", choices=["json", "markdown"], default="markdown")
    parser.add_argument("--output", help="Write report to file")
    return parser


def main() -> None:
    args = build_parser().parse_args()
    results = run_all_checks(root=Path(args.root))
    output = to_json(results) if args.format == "json" else to_markdown(results)
    if args.output:
        Path(args.output).write_text(output, encoding="utf-8")
    else:
        print(output)


if __name__ == "__main__":
    main()
EOF

write_file lhat/checks/ssh.py <<'EOF'
from pathlib import Path

from lhat.models import CheckResult, Status


def run(root: Path) -> list[CheckResult]:
    config = root / "etc/ssh/sshd_config"
    if not config.exists():
        return [CheckResult("SSH-001", "SSH config exists", Status.WARN, "sshd_config not found")]

    content = config.read_text(encoding="utf-8", errors="ignore")
    checks = []
    checks.append(
        CheckResult(
            "SSH-002",
            "Root login disabled",
            Status.PASS if "PermitRootLogin no" in content else Status.FAIL,
            "PermitRootLogin should be set to no",
            "Set PermitRootLogin no in /etc/ssh/sshd_config",
        )
    )
    checks.append(
        CheckResult(
            "SSH-003",
            "Password authentication disabled",
            Status.PASS if "PasswordAuthentication no" in content else Status.WARN,
            "PasswordAuthentication should be disabled when SSH keys are used",
            "Set PasswordAuthentication no after confirming key-based access",
        )
    )
    return checks
EOF

write_file lhat/checks/firewall.py <<'EOF'
from pathlib import Path

from lhat.models import CheckResult, Status


def run(root: Path) -> list[CheckResult]:
    firewalld = root / "usr/bin/firewall-cmd"
    ufw = root / "usr/sbin/ufw"
    nft = root / "usr/sbin/nft"
    if firewalld.exists() or ufw.exists() or nft.exists():
        return [CheckResult("FW-001", "Firewall tooling present", Status.PASS, "Firewall tooling detected")]
    return [
        CheckResult(
            "FW-001",
            "Firewall tooling present",
            Status.WARN,
            "No common firewall tooling detected",
            "Install and enable nftables, firewalld or ufw",
        )
    ]
EOF

write_file lhat/checks/users.py <<'EOF'
from pathlib import Path

from lhat.models import CheckResult, Status


def run(root: Path) -> list[CheckResult]:
    passwd = root / "etc/passwd"
    if not passwd.exists():
        return [CheckResult("USR-001", "passwd file exists", Status.WARN, "/etc/passwd not found")]
    risky = []
    for line in passwd.read_text(encoding="utf-8", errors="ignore").splitlines():
        parts = line.split(":")
        if len(parts) >= 7 and parts[2] == "0" and parts[0] != "root":
            risky.append(parts[0])
    if risky:
        return [CheckResult("USR-002", "Only root has UID 0", Status.FAIL, f"UID 0 users: {', '.join(risky)}")]
    return [CheckResult("USR-002", "Only root has UID 0", Status.PASS, "No extra UID 0 users found")]
EOF

write_file lhat/checks/sudo.py <<'EOF'
from pathlib import Path

from lhat.models import CheckResult, Status


def run(root: Path) -> list[CheckResult]:
    sudoers = root / "etc/sudoers"
    if not sudoers.exists():
        return [CheckResult("SUDO-001", "sudoers file exists", Status.WARN, "/etc/sudoers not found")]
    content = sudoers.read_text(encoding="utf-8", errors="ignore")
    status = Status.WARN if "NOPASSWD" in content else Status.PASS
    return [CheckResult("SUDO-002", "Passwordless sudo review", status, "Check NOPASSWD usage in sudoers")]
EOF

write_file lhat/checks/services.py <<'EOF'
from pathlib import Path

from lhat.models import CheckResult, Status


def run(root: Path) -> list[CheckResult]:
    systemd_dir = root / "etc/systemd/system"
    if systemd_dir.exists():
        return [CheckResult("SVC-001", "systemd configuration exists", Status.INFO, "systemd directory detected")]
    return [CheckResult("SVC-001", "systemd configuration exists", Status.WARN, "systemd directory not found")]
EOF

write_file lhat/checks/ports.py <<'EOF'
from pathlib import Path

from lhat.models import CheckResult, Status


def run(root: Path) -> list[CheckResult]:
    return [
        CheckResult(
            "PORT-001",
            "Open ports review",
            Status.INFO,
            "Run ss -tulpen on a live system to review listening services",
        )
    ]
EOF

write_file lhat/checks/updates.py <<'EOF'
from pathlib import Path

from lhat.models import CheckResult, Status


def run(root: Path) -> list[CheckResult]:
    apt_lists = root / "var/lib/apt/lists"
    if apt_lists.exists():
        return [CheckResult("UPD-001", "APT metadata exists", Status.INFO, "APT metadata directory found")]
    return [CheckResult("UPD-001", "APT metadata exists", Status.INFO, "Package manager metadata not detected")]
EOF

write_file lhat/checks/disk.py <<'EOF'
from pathlib import Path

from lhat.models import CheckResult, Status


def run(root: Path) -> list[CheckResult]:
    return [CheckResult("DISK-001", "Disk usage review", Status.INFO, f"Audit root path: {root}")]
EOF

write_file tests/test_runner.py <<'EOF'
from pathlib import Path

from lhat.runner import run_all_checks, to_markdown


def test_runner_returns_results(tmp_path: Path) -> None:
    etc_ssh = tmp_path / "etc/ssh"
    etc_ssh.mkdir(parents=True)
    (etc_ssh / "sshd_config").write_text("PermitRootLogin no\nPasswordAuthentication no\n", encoding="utf-8")
    results = run_all_checks(root=tmp_path)
    assert results
    assert "Linux Hardening Audit Report" in to_markdown(results)
EOF

commit_all "Add initial Python audit CLI and baseline checks"

git checkout develop
git merge --no-ff feature/initial-audit-cli -m "Merge feature/initial-audit-cli into develop"

# -----------------------------------------------------------------------------
# 3. Feature: CI pipeline
# -----------------------------------------------------------------------------

git checkout -b feature/ci-pipeline

write_file .github/workflows/ci.yml <<'EOF'
---
name: CI

on:
  push:
    branches:
      - main
      - develop
      - feature/**
      - fix/**
  pull_request:

jobs:
  lint-and-test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install pytest ruff

      - name: Run ruff
        run: ruff check .

      - name: Run tests
        run: pytest -q
EOF

commit_all "CI: Add GitHub Actions workflow for linting and tests"

git checkout develop
git merge --no-ff feature/ci-pipeline -m "Merge feature/ci-pipeline into develop"
git tag -a v0.1.0-baseline -m "Baseline Linux hardening audit toolkit"

# -----------------------------------------------------------------------------
# 4. Feature: report profiles and docs
# -----------------------------------------------------------------------------

git checkout -b feature/profiles-and-docs

write_file profiles/server-baseline.yml <<'EOF'
---
profile: server-baseline
description: Basic Linux server hardening profile
checks:
  ssh:
    require_root_login_disabled: true
    prefer_password_auth_disabled: true
  sudo:
    review_nopasswd: true
  users:
    fail_extra_uid_zero: true
EOF

write_file docs/checks.md <<'EOF'
# Checks

## SSH

- `SSH-001` verifies that `sshd_config` exists.
- `SSH-002` checks whether root login is disabled.
- `SSH-003` checks whether password authentication is disabled.

## Firewall

- `FW-001` detects common firewall tooling such as nftables, firewalld or ufw.

## Users and sudo

- `USR-002` detects non-root users with UID 0.
- `SUDO-002` reminds the operator to review `NOPASSWD` usage.

## Services, ports, updates and disk

These checks provide baseline operational visibility and point the administrator to live commands that should be reviewed on a real server.
EOF

write_file docs/usage.md <<'EOF'
# Usage

Run the audit locally:

```bash
python -m lhat.cli --format markdown
```

Generate JSON report:

```bash
python -m lhat.cli --format json --output reports/audit.json
```

Generate Markdown report:

```bash
python -m lhat.cli --format markdown --output reports/audit.md
```
EOF

write_file README.md <<'EOF'
# Linux Hardening Audit Toolkit

![CI](https://github.com/RM7hsh/linux-hardening-audit-toolkit/actions/workflows/ci.yml/badge.svg)

Linux security baseline audit toolkit for checking **SSH**, **firewall tooling**, **users**, **sudo**, **services**, **ports**, **updates**, **disk visibility** and general server hardening posture.

The project is built as a portfolio-ready Linux administration and security auditing tool. It demonstrates Python CLI structure, baseline security checks, report generation, tests, GitHub Actions CI and clean documentation.

---

## Features

- SSH hardening checks
- UID 0 user detection
- sudo `NOPASSWD` review
- firewall tooling detection
- systemd/service visibility checks
- open ports review guidance
- updates/package metadata checks
- Markdown and JSON report output
- pytest tests
- ruff linting
- GitHub Actions CI

---

## Quick start

```bash
python -m lhat.cli --format markdown
python -m lhat.cli --format json --output reports/audit.json
```

---

## Example output

```text
# Linux Hardening Audit Report

| Check | Status | Message |
|---|---|---|
| SSH-002 | PASS | PermitRootLogin should be set to no |
| SSH-003 | WARN | PasswordAuthentication should be disabled when SSH keys are used |
```

---

## Repository structure

```text
.
├── .github/workflows/ci.yml
├── docs/
├── lhat/
│   ├── checks/
│   ├── cli.py
│   ├── models.py
│   └── runner.py
├── profiles/
├── reports/
├── tests/
└── pyproject.toml
```

---

## What this project demonstrates

- practical Linux security baseline thinking
- Python CLI development
- structured audit checks
- clean report generation
- CI with ruff and pytest
- Git workflow with feature branches, merge commits and tags

---

## Author

**Rajabali Rahimov**  
GitHub: [https://github.com/RM7hsh](https://github.com/RM7hsh)
EOF

commit_all "Docs: add profiles, usage guide and detailed README"

git checkout develop
git merge --no-ff feature/profiles-and-docs -m "Merge feature/profiles-and-docs into develop"

# -----------------------------------------------------------------------------
# 5. Fix branch: improve live command support
# -----------------------------------------------------------------------------

git checkout -b feature/live-command-collectors

write_file lhat/shell.py <<'EOF'
import subprocess


def run_command(command: list[str], timeout: int = 5) -> tuple[int, str, str]:
    try:
        completed = subprocess.run(
            command,
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
        return completed.returncode, completed.stdout.strip(), completed.stderr.strip()
    except FileNotFoundError:
        return 127, "", f"command not found: {command[0]}"
    except subprocess.TimeoutExpired:
        return 124, "", "command timed out"
EOF

write_file lhat/live.py <<'EOF'
from lhat.models import CheckResult, Status
from lhat.shell import run_command


def collect_open_ports() -> CheckResult:
    code, stdout, stderr = run_command(["ss", "-tulpen"])
    if code == 0:
        lines = len(stdout.splitlines())
        return CheckResult("LIVE-PORTS", "Live open ports", Status.INFO, f"ss returned {lines} lines")
    return CheckResult("LIVE-PORTS", "Live open ports", Status.WARN, stderr or "ss command failed")


def collect_failed_units() -> CheckResult:
    code, stdout, stderr = run_command(["systemctl", "--failed", "--no-pager"])
    if code == 0:
        return CheckResult("LIVE-SYSTEMD", "Failed systemd units", Status.INFO, stdout or "No output")
    return CheckResult("LIVE-SYSTEMD", "Failed systemd units", Status.WARN, stderr or "systemctl failed")
EOF

python - <<'PY'
from pathlib import Path
path = Path('lhat/cli.py')
text = path.read_text(encoding='utf-8')
text = text.replace('    parser.add_argument("--output", help="Write report to file")\n', '    parser.add_argument("--output", help="Write report to file")\n    parser.add_argument("--live", action="store_true", help="Collect selected live command checks")\n')
text = text.replace('    results = run_all_checks(root=Path(args.root))\n', '    results = run_all_checks(root=Path(args.root))\n    if args.live:\n        from lhat.live import collect_failed_units, collect_open_ports\n\n        results.extend([collect_open_ports(), collect_failed_units()])\n')
path.write_text(text, encoding='utf-8')
PY

write_file tests/test_shell.py <<'EOF'
from lhat.shell import run_command


def test_run_command_handles_missing_binary() -> None:
    code, stdout, stderr = run_command(["definitely-not-existing-command-xyz"])
    assert code == 127
    assert stdout == ""
    assert "command not found" in stderr
EOF

commit_all "Add optional live command collectors for ports and systemd"

git checkout develop
git merge --no-ff feature/live-command-collectors -m "Merge feature/live-command-collectors into develop"
git tag -a v0.2.0-live-checks -m "Add optional live Linux command collectors"

# -----------------------------------------------------------------------------
# 6. Final docs and release
# -----------------------------------------------------------------------------

git checkout -b feature/final-docs

write_file docs/roadmap.md <<'EOF'
# Roadmap

Planned improvements:

- HTML report output
- Ansible playbook wrapper for fleet-wide audits
- CIS-like profile presets
- severity scoring
- remediation playbooks
- SSH authorized_keys audit
- package update count detection
- journald suspicious event checks
EOF

write_file LICENSE <<'EOF'
MIT License

Copyright (c) 2026 Rajabali Rahimov

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files, to deal in the Software
without restriction, including without limitation the rights to use, copy,
modify, merge, publish, distribute, sublicense, and/or sell copies of the
Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.
EOF

commit_all "Docs: add roadmap and license"

git checkout develop
git merge --no-ff feature/final-docs -m "Merge feature/final-docs into develop"

git checkout main
git merge --no-ff develop -m "Release v1.0.0: Linux hardening audit toolkit"
git tag -a v1.0.0 -m "First stable release of Linux Hardening Audit Toolkit"

cat <<'EOF'

Done. Git history created.

Next commands:
  git log --oneline --graph --decorate --all
  git push --all origin
  git push --tags origin

EOF

